-- AlterTable
ALTER TABLE "PlaybackState" ADD COLUMN     "eqGains" JSONB NOT NULL DEFAULT '[0,0,0,0,0]',
ADD COLUMN     "eqPitch" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "eqSpeed" DOUBLE PRECISION NOT NULL DEFAULT 1;
